[2024-12-01 01:05:17,967] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 01:05:18,333] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 02:54:37,332] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 02:54:37,720] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 03:39:13,284] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 03:39:13,697] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 04:02:13,584] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 04:02:13,941] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 04:34:58,219] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 04:34:58,577] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 04:50:27,502] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 04:50:27,844] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 05:11:23,886] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 05:11:24,245] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 05:30:58,126] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 05:30:58,455] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 05:47:39,245] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 05:47:39,552] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 06:15:47,125] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 06:15:47,464] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 06:44:07,632] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 06:44:08,026] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 06:53:05,772] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 06:53:06,113] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 07:10:39,264] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 07:10:39,589] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 07:27:39,205] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 07:27:39,541] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 07:37:58,203] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 07:37:58,669] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 07:47:40,686] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 07:47:41,032] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 08:13:51,649] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 08:13:52,045] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 08:33:39,546] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 08:33:39,909] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 08:49:52,737] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 08:49:53,094] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 09:11:06,695] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 09:11:07,073] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 09:27:42,748] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 09:27:43,097] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 09:37:06,163] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 09:37:06,508] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 09:47:32,348] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 09:47:32,685] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 10:11:45,086] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 10:11:45,483] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 10:33:30,848] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 10:33:31,174] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 10:47:48,714] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 10:47:49,123] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 11:09:12,670] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 11:09:12,955] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 11:23:02,663] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 11:23:03,022] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 11:33:40,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 11:33:40,759] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 11:47:55,178] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 11:47:55,459] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 12:20:15,106] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 12:20:15,407] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 12:56:58,875] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 12:56:59,241] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 13:21:26,301] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 13:21:26,665] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 13:38:43,541] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 13:38:43,853] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 13:47:50,511] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 13:47:50,913] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 14:09:25,541] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 14:09:25,893] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 14:29:13,943] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 14:29:14,287] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 14:39:56,600] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 14:39:57,006] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 14:47:43,558] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 14:47:43,954] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 15:10:18,541] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 15:10:18,885] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 15:27:56,472] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 15:27:56,883] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 15:37:26,599] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 15:37:26,936] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 15:47:32,535] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 15:47:32,979] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 16:12:49,347] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 16:12:49,665] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 16:34:27,036] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 16:34:27,400] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 16:49:57,764] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 16:49:58,110] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 17:09:35,758] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 17:09:36,118] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 17:27:56,798] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 17:27:57,155] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 17:37:43,260] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 17:37:43,678] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 17:47:38,053] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 17:47:38,371] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 18:14:04,064] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 18:14:04,421] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 18:36:00,742] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 18:36:02,251] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 18:49:45,493] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 18:49:45,834] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 19:08:22,540] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 19:08:22,978] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 19:21:47,233] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 19:21:47,595] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 19:33:50,766] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 19:33:51,076] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 19:47:47,131] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 19:47:47,468] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 20:11:46,864] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 20:11:47,244] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 20:28:59,628] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 20:28:59,989] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 20:39:26,758] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 20:39:27,091] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 20:47:36,067] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 20:47:36,421] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 21:09:59,770] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 21:10:00,035] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 21:25:42,415] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 21:25:42,760] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 21:34:13,569] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 21:34:13,976] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 21:47:58,112] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 21:47:58,463] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 22:10:21,192] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 22:10:21,557] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 22:30:35,538] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 22:30:36,011] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 22:47:35,451] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 22:47:35,787] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 23:10:42,308] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 23:10:42,672] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 23:26:46,979] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 23:26:47,324] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 23:36:00,984] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 23:36:02,168] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-01 23:47:40,769] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-01 23:47:41,107] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 00:57:53,905] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 00:57:54,278] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 02:27:39,492] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 02:27:39,862] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 03:23:58,403] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 03:23:58,804] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 03:49:41,810] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 03:49:42,112] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 04:14:21,188] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 04:14:21,548] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 04:35:54,298] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 04:35:54,648] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 04:50:58,811] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 04:50:59,225] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 05:12:34,287] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 05:12:34,626] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 05:32:42,639] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 05:32:43,048] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 05:47:44,913] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 05:47:45,265] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 06:17:26,983] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 06:17:27,395] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 06:46:25,318] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 06:46:25,744] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 07:12:21,435] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 07:12:21,826] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-02 07:30:00,488] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 07:30:03,668] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 07:41:36,522] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 07:41:38,663] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 07:48:56,354] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 07:48:58,870] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 08:16:44,298] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 08:16:46,770] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 08:44:21,041] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 08:44:23,389] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 08:55:03,690] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 08:55:05,749] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 09:13:30,047] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 09:13:33,022] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 09:33:55,293] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 09:33:59,241] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 09:47:56,311] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 09:47:59,401] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 10:13:36,280] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 10:13:38,308] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 10:37:38,865] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 10:37:41,721] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 10:50:57,313] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 10:51:01,212] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 11:10:13,878] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 11:10:15,920] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 11:25:01,515] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 11:25:03,849] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 11:34:04,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 11:34:07,639] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 11:47:47,541] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 11:47:50,604] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 12:23:06,056] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 12:23:08,917] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 13:02:02,544] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 13:02:05,030] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 13:37:16,180] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 13:37:18,861] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 13:49:13,296] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 13:49:15,928] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 14:11:33,006] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 14:11:35,766] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 14:33:17,518] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 14:33:20,021] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 14:49:16,849] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 14:49:18,929] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 15:12:35,658] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 15:12:38,417] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 15:32:03,704] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 15:32:06,579] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 15:48:19,632] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 15:48:22,575] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 16:14:28,468] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 16:14:31,726] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 16:40:26,646] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 16:40:29,584] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 16:53:46,680] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 16:53:49,468] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 17:10:35,016] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 17:10:37,805] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 17:29:54,510] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 17:29:57,983] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 17:41:13,531] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 17:41:16,512] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 17:48:44,539] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 17:48:47,380] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 18:16:00,324] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 18:16:03,079] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 18:44:55,565] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 18:44:58,877] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 18:52:22,382] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 18:52:25,474] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 19:09:37,866] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 19:09:40,907] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 19:23:09,423] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 19:23:12,409] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 19:34:06,972] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 19:34:10,092] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 19:47:41,989] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 19:47:44,915] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 20:11:45,448] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 20:11:48,732] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 20:30:16,018] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 20:30:18,828] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 20:41:41,858] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 20:41:44,969] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 20:49:11,849] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 20:49:14,482] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 21:10:56,370] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 21:10:58,779] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 21:27:23,846] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 21:27:26,736] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 21:37:17,885] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 21:37:20,215] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 21:47:31,664] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 21:47:34,423] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 22:11:14,883] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 22:11:17,639] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 22:32:20,658] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 22:32:23,202] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 22:47:37,028] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 22:47:39,500] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 23:12:53,928] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 23:12:56,298] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 23:30:08,317] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 23:30:11,205] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 23:41:20,315] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 23:41:22,747] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-02 23:48:41,917] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-02 23:48:44,809] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 00:57:04,529] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 00:57:06,963] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 02:25:32,905] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 02:25:35,350] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 03:23:00,328] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 03:23:02,092] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 03:48:43,734] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 03:48:46,627] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 04:14:04,150] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 04:14:07,670] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 04:35:43,300] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 04:35:45,336] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 04:50:59,897] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 04:51:02,853] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 05:12:11,909] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 05:12:15,009] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 05:32:04,354] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 05:32:06,806] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 05:47:46,736] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 05:47:49,020] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 06:17:27,333] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 06:17:30,933] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 06:46:26,083] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 06:46:28,498] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 07:11:40,555] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 07:11:43,090] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 07:29:11,779] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 07:29:15,477] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 07:39:30,505] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 07:39:33,070] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 07:47:36,808] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 07:47:39,756] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 08:15:33,120] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 08:15:36,070] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 08:43:09,437] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 08:43:12,606] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 08:53:38,447] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 08:53:41,439] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 09:13:02,665] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 09:13:08,363] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 09:31:41,589] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 09:31:43,857] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 09:47:46,678] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 09:47:48,624] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 10:13:19,596] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 10:13:22,026] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 10:37:54,309] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 10:37:57,309] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 10:51:08,158] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 10:51:11,906] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 11:10:21,369] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 11:10:25,185] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 11:25:14,826] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 11:25:17,855] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 11:34:02,140] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 11:34:05,323] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 11:47:48,525] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 11:47:51,720] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 12:21:58,722] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 12:22:01,800] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 13:00:55,198] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 13:00:58,347] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 13:36:48,083] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 13:36:50,233] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 13:48:55,196] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 13:48:57,491] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 14:10:51,238] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 14:11:15,396] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}
Traceback (most recent call last):
  File "id_data.py", line 92, in <module>
    gs = gc.open_by_key(sheetkey)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/gspread/client.py", line 170, in open_by_key
    return Spreadsheet(self, {"id": key})
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/gspread/spreadsheet.py", line 34, in __init__
    metadata = self.fetch_sheet_metadata()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/gspread/spreadsheet.py", line 254, in fetch_sheet_metadata
    r = self.client.request("get", url, params=params)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}
[2024-12-03 14:30:43,976] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 14:30:46,064] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 14:47:52,710] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 14:47:55,600] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 15:12:21,189] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 15:12:24,454] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 15:31:32,212] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 15:31:35,472] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 15:48:12,018] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 15:48:14,120] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 16:14:15,178] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 16:14:18,174] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 16:40:27,301] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 16:40:29,511] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 16:54:42,047] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 16:54:45,142] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 17:11:10,030] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 17:11:12,197] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 17:33:27,693] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 17:33:30,908] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 17:47:53,157] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 17:47:57,549] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 18:14:08,046] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 18:14:10,966] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 18:38:05,398] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 18:38:07,842] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 18:51:32,333] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 18:51:34,665] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 19:09:42,767] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 19:09:45,179] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 19:23:05,995] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 19:23:08,014] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 19:34:02,445] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 19:34:04,274] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 19:47:52,874] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 19:47:55,145] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 20:13:03,130] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 20:13:05,804] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 20:31:35,706] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 20:31:37,669] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 20:48:02,149] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 20:48:04,422] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 21:10:58,440] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 21:11:01,168] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 21:27:44,325] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 21:27:46,980] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 21:37:30,117] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 21:37:32,747] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 21:47:35,501] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 21:47:38,029] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 22:11:29,690] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 22:11:31,518] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 22:32:38,046] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 22:32:41,895] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 22:47:52,344] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 22:47:54,749] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 23:11:14,061] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 23:11:15,994] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 23:27:45,444] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 23:27:48,297] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 23:37:30,522] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 23:37:32,512] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-03 23:47:45,616] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-03 23:47:49,140] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 00:56:53,480] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 00:56:55,892] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 02:25:20,092] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 02:25:22,398] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 03:13:38,832] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 03:13:41,259] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 03:44:39,693] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 03:44:42,317] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 03:56:04,625] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 03:56:06,613] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 04:16:01,484] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 04:16:03,626] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 04:41:22,600] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 04:41:25,130] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 04:51:56,197] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 04:51:59,517] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 05:11:55,118] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 05:11:57,821] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 05:32:08,448] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 05:32:11,970] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 05:47:36,835] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 05:47:39,695] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 06:17:16,541] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 06:17:21,707] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 06:45:54,262] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 06:45:57,413] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 07:11:41,932] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 07:11:44,364] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 07:29:05,014] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 07:29:07,493] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 07:39:14,433] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 07:39:16,796] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 07:47:44,457] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 07:47:46,731] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 08:16:09,686] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 08:16:11,770] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 08:44:32,735] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 08:44:38,713] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 08:55:33,743] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 08:55:35,856] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 09:12:49,669] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 09:12:52,765] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 09:31:33,773] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 09:31:36,545] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 09:47:50,240] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 09:47:53,301] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 10:12:52,848] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 10:12:55,672] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 10:36:25,817] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 10:36:28,405] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 10:50:13,045] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 10:50:14,896] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 11:10:12,144] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 11:10:15,314] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 11:24:52,020] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 11:24:54,900] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 11:34:04,881] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 11:34:07,620] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 11:47:41,416] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 11:47:44,759] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 12:22:02,367] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 12:22:04,420] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 13:01:33,301] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 13:01:35,576] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 13:36:38,906] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 13:36:41,272] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 13:49:12,091] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 13:49:14,992] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 14:11:59,813] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 14:12:08,873] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 14:34:01,488] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 14:34:06,609] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 14:49:43,300] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 14:49:45,651] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 15:12:46,834] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 15:12:50,206] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 15:30:54,873] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 15:30:58,080] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 15:48:07,832] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 15:48:10,092] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 16:14:55,274] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 16:14:57,328] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 16:41:43,640] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 16:41:45,527] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 16:55:17,298] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 16:55:20,598] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 17:10:45,004] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 17:10:47,042] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 17:30:44,015] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 17:30:46,323] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 17:47:50,181] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 17:47:52,828] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 18:16:32,884] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 18:16:35,840] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 18:45:54,573] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 18:45:56,863] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 19:12:12,792] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 19:12:14,801] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 19:26:26,589] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 19:26:29,613] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 19:35:04,908] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 19:35:07,181] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 19:47:59,272] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 19:48:02,165] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 20:13:05,351] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 20:13:08,176] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 20:31:44,723] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 20:31:47,512] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 20:48:18,420] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 20:48:20,559] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 21:11:20,392] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 21:11:22,496] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 21:28:02,488] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 21:28:05,432] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 21:38:05,554] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 21:38:08,620] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 21:47:52,696] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 21:47:55,624] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 22:11:30,001] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 22:11:32,879] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 22:32:59,692] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 22:33:02,872] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 22:48:28,301] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 22:48:31,022] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 23:11:29,720] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 23:11:33,054] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 23:28:27,951] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 23:28:30,749] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 23:38:34,711] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 23:38:37,711] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-04 23:47:34,496] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-04 23:47:37,350] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-12-05 00:56:57,093] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 00:56:57,400] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 02:25:43,314] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 02:25:43,688] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 03:14:17,413] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 03:14:17,785] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 03:44:55,162] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 03:44:55,477] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 03:56:29,841] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 03:56:30,172] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 04:16:42,754] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 04:16:43,110] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 04:41:51,416] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 04:41:51,772] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 04:51:14,389] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 04:51:14,737] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 05:12:18,451] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 05:12:18,656] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 05:32:33,993] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 05:32:34,421] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 05:47:40,241] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 05:47:40,583] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 06:17:18,246] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 06:17:18,668] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 06:45:45,961] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 06:45:46,325] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 07:11:35,842] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 07:11:36,167] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 07:29:16,076] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 07:29:16,446] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 07:39:02,065] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 07:39:02,374] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 07:47:39,937] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 07:47:40,345] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 08:16:05,145] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 08:16:05,419] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 08:43:32,012] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 08:43:32,206] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 08:54:02,157] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 08:54:02,477] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 09:12:48,929] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 09:12:49,215] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 09:31:03,320] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 09:31:03,598] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 09:48:01,712] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 09:48:02,131] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 10:13:14,101] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 10:13:14,475] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 10:36:28,537] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 10:36:28,946] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 10:49:14,378] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 10:49:14,809] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 11:10:12,141] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 11:10:12,530] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 11:25:15,052] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 11:25:15,388] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 11:33:45,177] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 11:33:45,536] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 11:47:47,046] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 11:47:47,406] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 12:22:20,666] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 12:22:21,040] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 13:01:28,534] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 13:01:28,888] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 13:36:50,031] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 13:36:50,350] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 13:49:25,308] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 13:49:25,666] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 14:11:28,135] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 14:11:28,511] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 14:32:51,547] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 14:32:51,895] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 14:49:03,353] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 14:49:03,655] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 15:12:47,849] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 15:12:48,225] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 15:32:14,688] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 15:32:15,042] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 15:48:38,021] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 15:48:38,391] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 16:14:40,481] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 16:14:40,909] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 16:41:03,034] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 16:41:03,381] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 16:54:26,984] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 16:54:27,362] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 17:10:40,774] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 17:10:41,133] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 17:30:37,048] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 17:30:37,416] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 17:47:36,861] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 17:47:37,128] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 18:14:17,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 18:14:17,747] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 18:38:34,029] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 18:38:34,394] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 18:51:54,507] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 18:51:54,806] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 19:09:17,399] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 19:09:17,649] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 19:23:32,057] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 19:23:32,326] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 19:34:03,107] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 19:34:03,360] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 19:47:43,483] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 19:47:43,870] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 20:13:22,811] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 20:13:23,166] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 20:31:53,192] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 20:31:53,564] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 20:48:11,379] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 20:48:11,767] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 21:11:10,264] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 21:11:10,611] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 21:27:52,261] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 21:27:52,549] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 21:37:47,155] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 21:37:47,559] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 21:47:46,406] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 21:47:46,747] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 22:11:09,796] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 22:11:10,232] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 22:32:34,566] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 22:32:34,927] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 22:47:48,347] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 22:47:48,740] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 23:11:49,349] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 23:11:49,768] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 23:28:23,271] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 23:28:23,624] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 23:38:42,642] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 23:38:43,040] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-05 23:47:44,786] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-05 23:47:45,047] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 00:56:16,185] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 00:56:16,532] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 02:24:07,954] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 02:24:08,331] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 03:13:13,897] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 03:13:14,237] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 03:44:22,369] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 03:44:22,787] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 03:55:43,479] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 03:55:43,826] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 04:15:41,114] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 04:15:41,484] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 04:41:47,412] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 04:41:47,803] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 04:51:19,407] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 04:51:19,768] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 05:11:55,684] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 05:11:56,044] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 05:32:16,756] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 05:32:17,097] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 05:47:45,035] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 05:47:45,424] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 06:16:43,108] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 06:16:43,451] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 06:45:51,297] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 06:45:51,504] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 07:11:42,853] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 07:11:43,257] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 07:29:02,214] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 07:29:02,566] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 07:38:36,246] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 07:38:36,608] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 07:47:48,752] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 07:47:49,103] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 08:15:39,295] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 08:15:39,645] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 08:42:48,587] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 08:42:48,994] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 08:53:13,790] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 08:53:14,150] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 09:12:40,607] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 09:12:40,975] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 09:30:46,906] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 09:30:47,290] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 09:47:48,059] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 09:47:48,359] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 10:12:40,506] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 10:12:40,843] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 10:35:27,004] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 10:35:27,326] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 10:49:41,507] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 10:49:41,870] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 11:09:45,696] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 11:09:46,062] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 11:24:48,688] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 11:24:49,069] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 11:33:50,440] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 11:33:50,795] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 11:47:50,513] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 11:47:50,907] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 12:21:59,509] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 12:21:59,921] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 13:00:22,715] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 13:00:23,025] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 13:30:48,355] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 13:30:48,542] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 13:48:18,980] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 13:48:19,386] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 14:11:11,766] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 14:11:12,060] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 14:32:28,250] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 14:32:28,608] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 14:48:00,784] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 14:48:01,037] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 15:12:18,866] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 15:12:19,212] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 15:31:04,876] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 15:31:05,542] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 15:47:59,018] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 15:47:59,419] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 16:14:13,661] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 16:14:14,016] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 16:36:31,469] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 16:36:31,883] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 16:52:32,550] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 16:52:32,812] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 17:10:57,399] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 17:10:57,764] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 17:30:15,169] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 17:30:15,525] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 17:41:33,991] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 17:41:34,353] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 17:48:59,867] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 17:49:00,234] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 18:15:49,693] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 18:15:49,903] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 18:44:25,986] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 18:44:26,396] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 18:53:20,607] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 18:53:20,849] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 19:09:35,561] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 19:09:35,758] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 19:22:57,218] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 19:22:57,581] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 19:33:52,290] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 19:33:52,661] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 19:47:42,142] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 19:47:42,409] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 20:13:05,506] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 20:13:05,816] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 20:31:17,519] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 20:31:17,899] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 20:47:39,271] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 20:47:39,618] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 21:10:43,775] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 21:10:44,131] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 21:27:11,905] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 21:27:12,257] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 21:37:07,756] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 21:37:08,105] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 21:48:00,418] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 21:48:00,821] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 22:11:15,565] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 22:11:15,895] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 22:32:18,313] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 22:32:18,532] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 22:47:41,857] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 22:47:42,230] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 23:11:16,370] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 23:11:16,674] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 23:27:48,808] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 23:27:49,078] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 23:37:28,617] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 23:37:28,828] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-06 23:47:49,953] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-06 23:47:50,256] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 00:55:56,598] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 00:55:56,974] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 02:22:02,637] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 02:22:02,984] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 03:12:09,375] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 03:12:09,588] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 03:43:36,577] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 03:43:36,926] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 03:54:46,672] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 03:54:47,035] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 04:14:02,963] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 04:14:03,271] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 04:34:31,380] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 04:34:31,674] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 04:49:48,117] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 04:49:48,527] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 05:11:11,344] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 05:11:11,680] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 05:30:58,339] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 05:30:58,647] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 05:47:50,124] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 05:47:50,324] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 06:15:15,355] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 06:15:15,642] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 06:39:24,449] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 06:39:24,761] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 06:51:01,924] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 06:51:02,290] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 07:10:26,649] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 07:10:26,990] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 07:27:06,239] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 07:27:06,536] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 07:36:49,130] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 07:36:49,525] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 07:47:50,770] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 07:47:51,063] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 08:13:50,897] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 08:13:51,227] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 08:33:56,513] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 08:33:56,971] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 08:49:53,494] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 08:49:53,895] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 09:11:10,897] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 09:11:11,268] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 09:27:48,787] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 09:27:49,206] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 09:37:24,784] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 09:37:25,088] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 09:47:44,772] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 09:47:45,172] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 10:12:02,407] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 10:12:02,742] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 10:33:59,370] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 10:33:59,787] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 10:47:54,451] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 10:47:54,661] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 11:09:43,781] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 11:09:44,132] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 11:22:57,629] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 11:22:57,938] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 11:33:57,135] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 11:33:57,322] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 11:47:43,183] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 11:47:43,569] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 12:19:59,453] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 12:19:59,736] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 12:56:47,035] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 12:56:47,235] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 13:20:30,769] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 13:20:31,069] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 13:37:38,547] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 13:37:38,887] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 13:47:53,930] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 13:47:54,215] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 14:09:37,896] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 14:09:38,152] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 14:29:14,318] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 14:29:14,616] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 14:39:44,638] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 14:39:44,947] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 14:47:47,251] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 14:47:47,582] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 15:10:34,088] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 15:10:34,457] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 15:27:41,668] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 15:27:42,021] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 15:37:15,129] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 15:37:15,498] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 15:47:39,024] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 15:47:39,354] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 16:12:42,349] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 16:12:42,694] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 16:34:49,496] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 16:34:49,698] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 16:50:15,890] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 16:50:16,307] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 17:09:10,824] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 17:09:11,119] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 17:27:40,308] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 17:27:40,724] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 17:37:11,366] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 17:37:11,654] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 17:47:39,046] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 17:47:39,321] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 18:14:23,908] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 18:14:24,240] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 18:36:41,954] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 18:36:42,315] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 18:49:41,465] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 18:49:41,853] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 19:08:30,772] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 19:08:31,121] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 19:21:25,757] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 19:21:26,108] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 19:33:48,436] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 19:33:48,801] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 19:47:51,739] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 19:47:52,107] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 20:11:30,802] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 20:11:31,166] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 20:28:59,214] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 20:28:59,584] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 20:38:50,855] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 20:38:51,256] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 20:47:55,237] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 20:47:55,608] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 21:09:58,119] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 21:09:58,419] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 21:25:40,638] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 21:25:41,054] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 21:33:49,767] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 21:33:50,069] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 21:47:53,628] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 21:47:53,977] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 22:10:17,632] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 22:10:18,074] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 22:30:37,724] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 22:30:38,174] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 22:47:32,936] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 22:47:33,292] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 23:10:43,767] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 23:10:43,961] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 23:26:23,884] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 23:26:24,492] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 23:35:25,135] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 23:35:25,365] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-07 23:47:42,615] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-07 23:47:42,907] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-08 01:01:07,614] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-08 01:01:07,915] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-08 02:47:05,992] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-08 02:47:06,399] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-08 03:32:46,527] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-08 03:32:46,886] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-08 03:55:09,437] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-08 03:55:09,731] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-08 04:13:52,142] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-08 04:13:52,489] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-08 04:34:20,475] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-08 04:34:20,822] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-08 04:49:30,566] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-08 04:49:30,950] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-08 05:11:11,840] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-08 05:11:12,254] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-08 05:30:46,579] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-08 05:30:46,862] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-08 05:47:48,023] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-08 05:47:48,315] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-08 06:15:11,977] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-08 06:15:12,338] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-08 06:39:34,095] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-08 06:39:34,400] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-12-08 06:51:17,871] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-12-08 06:51:18,224] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
